# Generated by Django 5.2.17 on 2026-09-19 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitales', '0001_initial'),
        ('medicos', '0002_disponibilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='hospitales.especialidad')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='hospitales.hospital')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
