# Generated by Django 5.2.17 on 2026-09-19 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('hospitales', '0001_initial'),
        ('medicos', '0003_bloqueohorario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha_hora'), name='cita_medico_fecha_unica'),
        ),
    ]
