# Generated by Django 5.2.17 on 2026-09-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_cita_medico_fecha_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='numero_turno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
