# Generated by Django 5.2.17 on 2026-09-19 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_numero_turno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='numero_turno',
        ),
        migrations.CreateModel(
            name='OfertaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptada', models.BooleanField(blank=True, null=True)),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True)),
                ('cita_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='citas.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas_cita', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
