# Generated by Django 5.2.17 on 2026-10-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_remove_cita_numero_turno_ofertacita'),
        ('hospitales', '0001_initial'),
        ('medicos', '0003_bloqueohorario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertacita',
            name='cita_origen',
        ),
        migrations.CreateModel(
            name='HorarioLiberado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_liberacion', models.DateTimeField(auto_now_add=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_liberados', to='hospitales.especialidad')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_liberados', to='hospitales.hospital')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_liberados', to='medicos.medico')),
            ],
        ),
        migrations.AddField(
            model_name='ofertacita',
            name='horario_liberado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='citas.horarioliberado'),
        ),
    ]
