# Generated by Django 5.2.17 on 2026-10-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0005_remove_ofertacita_cita_origen_horarioliberado_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cita",
            name="cita_medico_fecha_unica",
        ),
    ]
