# Generated by Django 5.2.17 on 2026-10-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0005_remove_ofertacita_cita_origen_horarioliberado_and_more"),
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="oferta_cita",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notificaciones",
                to="citas.ofertacita",
            ),
        ),
    ]
