# Generated by Django 5.2.17 on 2026-10-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0002_notificacion_oferta_cita"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="leida",
            field=models.BooleanField(default=False),
        ),
    ]
